/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examportal;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author HP
 */
public class ConductExamFrame1 extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form ConductExamFrame1
     */
   
    String subject;
    String level;
    int numberOfQuestions;
    int duration;
    int time;
    Exam exam;
    int currentIndex = 0;
    
    
    public ConductExamFrame1(String subject, String level, int numberOfQuestions, int duration) {
        initComponents();
        this.subject = subject;
        this.level = level;
        this.numberOfQuestions = numberOfQuestions;
        this.duration = duration;
        time = duration * 60;
        exam = new Exam(subject, level, numberOfQuestions);
        tr = new Timer(1000,this);
    }

    public void actionPerformed(ActionEvent ae) {
        if (time >= 1) {
            time--;
        }
        updateLabel();
        if (time == 0) {
            tr.stop();
            JOptionPane.showMessageDialog(this, "Time Over\nYour Exam will now Finish");
            finishExam();
        }
    }

    private void updateLabel() {
        lblTimeRemaining.setText("Time Remaining : " + time / 60 + " Minutes " + time % 60 + " Seconds");
    }

    private void finishExam() {
        updateAnswer();
        ExamReport report = new ExamReport();
        report.setStudentName(System.getProperty("userName"));
        DateFormat fmt = new SimpleDateFormat("dd/MMMMM/yyyy");
        report.setExamDate(fmt.format(new java.util.Date()));
        report.setSubject(subject);
        report.setLevel(level);
        report.setNumberOfQuestions(numberOfQuestions);
        report.setAttempted(exam.getAttemptedQuestions());
        report.setCorrect(exam.getCorrectQuestions());
        dbManager.saveReport(report);
        ReportFrame1 f = new ReportFrame1(report);
        f.setLocationRelativeTo(null);
        f.setParentFrame(parent);
        f.setVisible(true);
        tr.stop();
        ((MainFrame) parent).setChild(f);
        dispose();
    }

    private void updateAnswer() {
        Question q = exam.getQuestion(currentIndex);
        if (rboOptionA.isSelected()) {
            q.setUserAnswer("A");
        }
        if (rboOptionB.isSelected()) {
            q.setUserAnswer("B");
        }
        if (rboOptionC.isSelected()) {
            q.setUserAnswer("C");
        }
        if (rboOptionD.isSelected()) {
            q.setUserAnswer("D");
        }
    }

    private void setQuestion() {
        lblQNo.setText("Q.No. " + (currentIndex + 1) + " : ");
        Question q = exam.getQuestion(currentIndex);
        txtQuestionText.setText(q.getQuestionText());
        rboOptionA.setText(q.getOptionA());
        rboOptionB.setText(q.getOptionB());
        rboOptionC.setText(q.getOptionC());
        rboOptionD.setText(q.getOptionD());
        if (q.getUserAnswer().equals("")) {
            grpoption.clearSelection();
        } else {
            if (q.getUserAnswer().equals("A")) {
                rboOptionA.setSelected(true);
            } else if (q.getUserAnswer().equals("B")) {
                rboOptionB.setSelected(true);
            } else if (q.getUserAnswer().equals("C")) {
                rboOptionC.setSelected(true);
            } else if (q.getUserAnswer().equals("D")) {
                rboOptionD.setSelected(true);
            }
        }

        if (currentIndex == 0) {
            btnPrevious.setEnabled(false);
        } else {
            btnPrevious.setEnabled(true);
        }
        if (currentIndex == numberOfQuestions - 1) {
            btnNext.setEnabled(false);
        } else {
            btnNext.setEnabled(true);
        }
    }

    public void setParentFrame(JFrame f) {
        parent = f;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpoption = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblNumberOfQuestions = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestionText = new javax.swing.JTextArea();
        lblTimeRemaining = new javax.swing.JLabel();
        lblQNo = new javax.swing.JLabel();
        rboOptionA = new javax.swing.JRadioButton();
        rboOptionB = new javax.swing.JRadioButton();
        rboOptionC = new javax.swing.JRadioButton();
        rboOptionD = new javax.swing.JRadioButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnFinish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 255, 102));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        lblNumberOfQuestions.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumberOfQuestions.setForeground(new java.awt.Color(255, 255, 255));
        lblNumberOfQuestions.setText("jLabel2");

        lblSubject.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSubject.setForeground(new java.awt.Color(255, 255, 255));
        lblSubject.setText("jLabel1");
        lblSubject.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblDuration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDuration.setForeground(new java.awt.Color(255, 255, 255));
        lblDuration.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumberOfQuestions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDuration)
                .addGap(71, 71, 71))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(lblSubject)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumberOfQuestions)
                    .addComponent(lblDuration))
                .addContainerGap())
        );

        txtQuestionText.setColumns(20);
        txtQuestionText.setRows(5);
        jScrollPane1.setViewportView(txtQuestionText);

        lblTimeRemaining.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTimeRemaining.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeRemaining.setText("jLabel1");
        lblTimeRemaining.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblQNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQNo.setForeground(new java.awt.Color(255, 255, 255));
        lblQNo.setText("jLabel1");
        lblQNo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        grpoption.add(rboOptionA);

        grpoption.add(rboOptionB);

        grpoption.add(rboOptionC);

        grpoption.add(rboOptionD);

        btnPrevious.setBackground(new java.awt.Color(0, 255, 204));
        btnPrevious.setForeground(new java.awt.Color(255, 51, 51));
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setForeground(new java.awt.Color(255, 51, 51));
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnFinish.setForeground(new java.awt.Color(255, 51, 51));
        btnFinish.setText("Finish");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTimeRemaining)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblQNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rboOptionA)
                    .addComponent(rboOptionD)
                    .addComponent(rboOptionC)
                    .addComponent(rboOptionB))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblTimeRemaining)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQNo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(rboOptionA)
                        .addGap(18, 18, 18)
                        .addComponent(rboOptionB)
                        .addGap(18, 18, 18)
                        .addComponent(rboOptionC)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(rboOptionD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Do you really want to FINISH your exam", "Warning", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            finishExam();
        }
    }//GEN-LAST:event_btnFinishActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        updateAnswer();
        if (currentIndex < numberOfQuestions - 1) {
            currentIndex++;
            setQuestion();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        updateAnswer();
        if (currentIndex >= 1) {
            currentIndex--;
            setQuestion();
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         lblSubject.setText("Subject : " + subject);
        lblNumberOfQuestions.setText("Number of Questions : " + numberOfQuestions);
        lblDuration.setText("Duration : " + duration + " Minutes");
        tr.start();
        setQuestion();
        updateLabel();
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.ButtonGroup grpoption;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblNumberOfQuestions;
    private javax.swing.JLabel lblQNo;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTimeRemaining;
    private javax.swing.JRadioButton rboOptionA;
    private javax.swing.JRadioButton rboOptionB;
    private javax.swing.JRadioButton rboOptionC;
    private javax.swing.JRadioButton rboOptionD;
    private javax.swing.JTextArea txtQuestionText;
    // End of variables declaration//GEN-END:variables
 private JFrame parent;
    private Timer tr;
}
