/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examportal;
import java.util.*;  
//import javax.mail.*;  
//import javax.mail.internet.*;  
import javax.activation.*;  
import com.mysql.jdbc.interceptors.SessionAssociationInterceptor;
import java.awt.AWTException;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import static java.lang.String.format;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import java.awt.Robot;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author HP
 */
public class ReportFrame1 extends javax.swing.JFrame implements Printable{

    /**
     * Creates new form ReportFrame1
     */private ExamReport report;
    // final Component comp;
     MainClass mc=new MainClass();
     Connection conn;
     int ReportID=0;
     
    public ReportFrame1(ExamReport report) {
        initComponents();
        
         this.report = report;
        int StudentId=report.getUserID();
        lblStudentName.setText(""+report.getFirstName());
        lblExamDate.setText(report.getExamDate());
        lblSubject.setText(report.getSubject());
        lblLevel.setText(report.getLevel());
        lblNumberOfQuestions.setText("" + report.getNumberOfQuestions());
        lblAttempted.setText("" + report.getAttempted());
        lblCorrect.setText("" + report.getCorrect());
        lblScore.setText("" + report.getScore() + "%");
    }
    public void setParentFrame(JFrame f) {
        parent = f;
    }

   /* public ReportFrame1(ExamReport report) {
        initComponents();
        this.report = report;
        lblStudentName.setText(report.getStudentName());
        lblExamDate.setText(report.getExamDate());
        lblSubject.setText(report.getSubject());
        lblLevel.setText(report.getLevel());
        lblNumberOfQuestions.setText("" + report.getNumberOfQuestions());
        lblAttempted.setText("" + report.getAttempted());
        lblCorrect.setText("" + report.getCorrect());
        lblScore.setText("" + report.getScore() + "%");
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        repopanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        lblExamDate = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNumberOfQuestions = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAttempted = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prpanel = new javax.swing.JPanel();
        prlabel = new javax.swing.JLabel();
        clpanel = new javax.swing.JPanel();
        cllabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        repopanel.setBackground(new java.awt.Color(153, 255, 51));
        repopanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Exam Report");

        lblScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblScore.setForeground(new java.awt.Color(255, 255, 255));
        lblScore.setText("jLabel15");
        lblScore.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correct : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Level : ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Score : ");

        lblLevel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLevel.setForeground(new java.awt.Color(255, 255, 255));
        lblLevel.setText("jLabel10");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Student Name : ");

        lblStudentName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentName.setText("jLabel9");

        lblExamDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblExamDate.setForeground(new java.awt.Color(255, 255, 255));
        lblExamDate.setText("jLabel10");

        lblSubject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSubject.setForeground(new java.awt.Color(255, 255, 255));
        lblSubject.setText("jLabel11");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date : ");

        lblNumberOfQuestions.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumberOfQuestions.setForeground(new java.awt.Color(255, 255, 255));
        lblNumberOfQuestions.setText("jLabel12");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Subject : ");

        lblAttempted.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAttempted.setForeground(new java.awt.Color(255, 255, 255));
        lblAttempted.setText("jLabel13");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Number of Questions : ");

        lblCorrect.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCorrect.setForeground(new java.awt.Color(255, 255, 255));
        lblCorrect.setText("jLabel14");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Attempted : ");

        prpanel.setBackground(new java.awt.Color(0, 102, 0));
        prpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prpanelMouseClicked(evt);
            }
        });

        prlabel.setForeground(new java.awt.Color(255, 255, 255));
        prlabel.setText("Print Report");
        prlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prlabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout prpanelLayout = new javax.swing.GroupLayout(prpanel);
        prpanel.setLayout(prpanelLayout);
        prpanelLayout.setHorizontalGroup(
            prpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prpanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(prlabel)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        prpanelLayout.setVerticalGroup(
            prpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prlabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clpanel.setBackground(new java.awt.Color(0, 102, 0));
        clpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clpanelMouseClicked(evt);
            }
        });

        cllabel.setForeground(new java.awt.Color(255, 255, 255));
        cllabel.setText("Close");
        cllabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cllabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout clpanelLayout = new javax.swing.GroupLayout(clpanel);
        clpanel.setLayout(clpanelLayout);
        clpanelLayout.setHorizontalGroup(
            clpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clpanelLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(cllabel)
                .addGap(50, 50, 50))
        );
        clpanelLayout.setVerticalGroup(
            clpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cllabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout repopanelLayout = new javax.swing.GroupLayout(repopanel);
        repopanel.setLayout(repopanelLayout);
        repopanelLayout.setHorizontalGroup(
            repopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, repopanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(220, 220, 220))
            .addGroup(repopanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(prpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(clpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(repopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(repopanelLayout.createSequentialGroup()
                    .addGap(152, 152, 152)
                    .addGroup(repopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                    .addGroup(repopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLevel)
                        .addComponent(lblSubject)
                        .addComponent(lblStudentName)
                        .addComponent(lblExamDate)
                        .addComponent(lblNumberOfQuestions)
                        .addComponent(lblAttempted)
                        .addComponent(lblCorrect)
                        .addComponent(lblScore))
                    .addGap(153, 153, 153)))
        );
        repopanelLayout.setVerticalGroup(
            repopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repopanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 469, Short.MAX_VALUE)
                .addGroup(repopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69))
            .addGroup(repopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(repopanelLayout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addGroup(repopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(repopanelLayout.createSequentialGroup()
                            .addGroup(repopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(lblStudentName))
                            .addGap(29, 29, 29)
                            .addGroup(repopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(lblExamDate))
                            .addGap(32, 32, 32)
                            .addComponent(jLabel3)
                            .addGap(33, 33, 33)
                            .addGroup(repopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(lblLevel))
                            .addGap(40, 40, 40)
                            .addGroup(repopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(lblNumberOfQuestions))
                            .addGap(34, 34, 34)
                            .addGroup(repopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(lblAttempted))
                            .addGap(45, 45, 45))
                        .addGroup(repopanelLayout.createSequentialGroup()
                            .addComponent(lblSubject)
                            .addGap(200, 200, 200)))
                    .addGroup(repopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(lblCorrect))
                    .addGap(33, 33, 33)
                    .addGroup(repopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(lblScore))
                    .addContainerGap(153, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(repopanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(repopanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(611, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clpanelMouseClicked
   try {
        String format = "png";
        String fileName = "Repo1." + format;
BufferedImage captureImage=new BufferedImage(repopanel.getWidth(), repopanel.getHeight(), BufferedImage.TYPE_INT_RGB);
        repopanel.paint(captureImage.getGraphics());
        File opfile=new File("C:\\Users\\HP\\Desktop\\"+fileName);
        ImageIO.write(captureImage, format, opfile);
 
       
    } catch (IOException ex) {
        System.err.println(ex);
    }
      /*  String to="himanshumech77@gmail.com";
         final String user="himanshumech75@gmail.com";
         final String password="peehupeehu";
         Properties prop=System.getProperties();
         prop.setProperty("mail.smtp.host","mail.gmail.com");
         prop.put("mail.smtp.auth", true);
        Session session = Session.getDefaultInstance(prop,  
        new javax.mail.Authenticator() {  
        protected PasswordAuthentication getPasswordAuthentication() {  
        return new PasswordAuthentication(user,password);  
   }  
  });
        try{  
    MimeMessage message = new MimeMessage(session);  
    message.setFrom(new InternetAddress(user));  
    message.addRecipient(Message.RecipientType.TO,new InternetAddress(to));  
    message.setSubject("Exam Report");  
     BodyPart messageBodyPart1 = new MimeBodyPart();  
    messageBodyPart1.setText("This is message body");   
    MimeBodyPart messageBodyPart2 = new MimeBodyPart();  
  
    String filename = "Repo.jpeg";//change accordingly  
    DataSource source = new FileDataSource(filename);  
    messageBodyPart2.setDataHandler(new DataHandler(source));  
    messageBodyPart2.setFileName(filename);
    
    Multipart multipart = new MimeMultipart();  
    multipart.addBodyPart(messageBodyPart1);  
    multipart.addBodyPart(messageBodyPart2);  
    
    message.setContent(multipart ); 
     Transport.send(message);  
   
   System.out.println("message sent....");  
   }catch (MessagingException ex) {ex.printStackTrace();}  
        System.exit(0);*/
    
    }//GEN-LAST:event_clpanelMouseClicked

    private void cllabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cllabelMouseClicked
    try {
        String format = "png";
        String fileName = "Repo1." + format;
BufferedImage captureImage=new BufferedImage(repopanel.getWidth(), repopanel.getHeight(), BufferedImage.TYPE_INT_RGB);
        repopanel.paint(captureImage.getGraphics());
        File opfile=new File("C:\\Users\\HP\\Desktop\\"+fileName);
        ImageIO.write(captureImage, format, opfile);
 
       
    } catch (IOException ex) {
        System.err.println(ex);
    }
       /* String to="himanshumech77@gmail.com";
         final String user="himanshumech75@gmail.com";
         final String password="peehupeehu";
         Properties prop=System.getProperties();
         prop.setProperty("mail.smtp.gmail.com","mail.smtp.gmail.com");
         prop.put("mail.smtp.auth", true);
        Session session = Session.getDefaultInstance(prop,  
        new javax.mail.Authenticator() {  
        protected PasswordAuthentication getPasswordAuthentication() {  
        return new PasswordAuthentication(user,password);  
   }  
  });
        try{  
    MimeMessage message = new MimeMessage(session);  
    message.setFrom(new InternetAddress(user));  
    message.addRecipient(Message.RecipientType.TO,new InternetAddress(to));  
    message.setSubject("Exam Report");  
     BodyPart messageBodyPart1 = new MimeBodyPart();  
    messageBodyPart1.setText("This is message body");   
    MimeBodyPart messageBodyPart2 = new MimeBodyPart();  
  
    String filename = "Repo.jpeg";//change accordingly  
    DataSource source = new FileDataSource("C:\\Users\\HP\\Desktop\\"+filename);  
    messageBodyPart2.setDataHandler(new DataHandler(source));  
    messageBodyPart2.setFileName(filename);
    
    Multipart multipart = new MimeMultipart();  
    multipart.addBodyPart(messageBodyPart1);  
    multipart.addBodyPart(messageBodyPart2);  
    
    message.setContent(multipart ); 
     Transport.send(message);  
   
   System.out.println("message sent....");  
   }catch (MessagingException ex) {ex.printStackTrace();}  
        System.exit(0);*/
        
    }//GEN-LAST:event_cllabelMouseClicked

    private void prpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prpanelMouseClicked
        // TODO add your handling code here:
         PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable((Printable) this);
        boolean ok = job.printDialog();
        if (ok) {
            try {
                job.print();
            } catch (PrinterException ex) {
                /* The job did not successfully complete */
            }
        }
    }//GEN-LAST:event_prpanelMouseClicked

    private void prlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prlabelMouseClicked
        // TODO add your handling code here:
         PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable((Printable) this);
        boolean ok = job.printDialog();
        if (ok) {
            try {
                job.print();
            } catch (PrinterException ex) {
                /* The job did not successfully complete */
            }
        }
    }//GEN-LAST:event_prlabelMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       /* // TODO add your handling code here:         
         String to="himanshumech77@gmail.com";
         final String user="himanshumech75@gmail.com";
         final String password="peehupeehu";
         Properties prop=System.getProperties();
         prop.setProperty("mail.smtp.gmail.com","mail.smtp.gmail.com");
         prop.put("mail.smtp.auth", true);
        Session session = Session.getDefaultInstance(prop,  
        new javax.mail.Authenticator() {  
        protected PasswordAuthentication getPasswordAuthentication() {  
        return new PasswordAuthentication(user,password);  
   }  
  });
        try{  
    MimeMessage message = new MimeMessage(session);  
    message.setFrom(new InternetAddress(user));  
    message.addRecipient(Message.RecipientType.TO,new InternetAddress(to));  
    message.setSubject("Exam Report");  
     BodyPart messageBodyPart1 = new MimeBodyPart();  
    messageBodyPart1.setText("This is message body");   
    MimeBodyPart messageBodyPart2 = new MimeBodyPart();  
  
    String filename = "Repo1.png";//change accordingly  
    DataSource source = new FileDataSource("C:\\Users\\HP\\Desktop\\"+filename);  
    messageBodyPart2.setDataHandler(new DataHandler(source));  
    messageBodyPart2.setFileName(filename);
    
    Multipart multipart = new MimeMultipart();  
    multipart.addBodyPart(messageBodyPart1);  
    multipart.addBodyPart(messageBodyPart2);  
    
    message.setContent(multipart ); 
     Transport.send(message);  
   
   System.out.println("message sent....");  
   }catch (MessagingException ex) {ex.printStackTrace();}*/
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         try {
             // TODO add your handling code here:
             conn=DriverManager.getConnection(mc.StrUrl,mc.StrUser, mc.StrPwd);
             String st="";
             try (PreparedStatement ps2=conn.prepareStatement("Insert into Reports(ReportId,UserId,UserName,ExamDate,Subject,Level,TotalQuestions,CoreectQuestions,Score) values(?,?,?,?,?,?,?,?,?)")){
                 ps2.setString(1,""+ReportID);
                 ps2.setString(2,StudentID);
                 ps2.setString(3,lblStudentName.getText());
                 ps2.setString(4,lblExamDate.getText());
                 ps2.setString(5,lblSubject.getText());
                 ps2.setString(6,lblLevel.getText());
                 ps2.setString(7,lblNumberOfQuestions.getText());
                 ps2.setString(8,lblCorrect.getText());
                 ps2.setString(9,lblScore.getText());
                 ps2.executeUpdate();
             }
         } catch (SQLException ex) {
             Logger.getLogger(ReportFrame1.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_formWindowOpened
   
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cllabel;
    private javax.swing.JPanel clpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAttempted;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblExamDate;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblNumberOfQuestions;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel prlabel;
    private javax.swing.JPanel prpanel;
    private javax.swing.JPanel repopanel;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JFrame parent;

   
    @Override
     public int print(Graphics g, PageFormat format, int pagenum) {
         
       if (pagenum > 0){
           return Printable.NO_SUCH_PAGE;
       }
        
       g.translate((int)format.getImageableX(), (int)format.getImageableY());
               
       float pageWidth = (float)format.getImageableWidth();
       float pageHeight = (float)format.getImageableHeight();
        
       float imageHeight = (float)this.getHeight();
       float imageWidth = (float)this.getWidth();
        
       float scaleFactor = Math.min((float)pageWidth/(float)imageWidth, (float)pageHeight/(float)imageHeight);
  
       int scaledWidth = (int)(((float)imageWidth)*scaleFactor);
        
       int scaledHeight = (int)(((float)imageHeight)*scaleFactor);  
        
       BufferedImage canvas = new BufferedImage( this.getWidth(),  this.getHeight(), BufferedImage.TYPE_INT_RGB);
       Graphics2D gg = canvas.createGraphics();
       this.paint( gg );  
       Image img = canvas ;
  
       g.drawImage(img, 0, 0, scaledWidth, scaledHeight, null );
  
       return Printable.PAGE_EXISTS;
        
    }
 
   
}
