/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examportal;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class SelectExamFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form SelectExamFrame1
     */
    public SelectExamFrame1() {
        initComponents();
    }
  public void setParentFrame(JFrame f){
        parent = f;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboSubjects = new javax.swing.JComboBox();
        spnNumberOfQuestions = new javax.swing.JSpinner();
        cboDifficultyLevel = new javax.swing.JComboBox();
        spnDuration = new javax.swing.JSpinner();
        StartPanel = new javax.swing.JPanel();
        Startlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select an Exam");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Subject : ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Number of Questions :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Difficulty Level :");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Duration (in Minutes) : ");

        cboSubjects.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        spnNumberOfQuestions.setModel(new javax.swing.SpinnerNumberModel(5, 5, 25, 5));

        cboDifficultyLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        spnDuration.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));

        StartPanel.setBackground(new java.awt.Color(255, 0, 0));
        StartPanel.setForeground(new java.awt.Color(204, 0, 204));
        StartPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartPanelMouseClicked(evt);
            }
        });

        Startlabel.setForeground(new java.awt.Color(255, 255, 255));
        Startlabel.setText("Start Exam");
        Startlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartlabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout StartPanelLayout = new javax.swing.GroupLayout(StartPanel);
        StartPanel.setLayout(StartPanelLayout);
        StartPanelLayout.setHorizontalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Startlabel)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        StartPanelLayout.setVerticalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Startlabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(spnNumberOfQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboSubjects, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboDifficultyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(StartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cboSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnNumberOfQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addComponent(cboDifficultyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(StartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(409, 361));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StartlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartlabelMouseClicked
        // TODO add your handling code here:
        String subject = cboSubjects.getSelectedItem().toString();
        String level = cboDifficultyLevel.getSelectedItem().toString();
        int numberOfQuestions = (Integer)spnNumberOfQuestions.getValue();
        Exam exam = new Exam(subject, level, numberOfQuestions);
        if(exam.list.size()<numberOfQuestions){
            JOptionPane.showMessageDialog(this, "Not Enough Questions in the Database","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int duration = (Integer)spnDuration.getValue();
        ConductExamFrame1 f = new ConductExamFrame1(subject,level,numberOfQuestions,duration);
        f.setLocationRelativeTo(null);
        f.setParentFrame(parent);
        f.setVisible(true);
        this.setVisible(false);
        ((MainFrame)parent).setChild(f);
        dispose();
    }//GEN-LAST:event_StartlabelMouseClicked

    private void StartPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartPanelMouseClicked
        // TODO add your handling code here:
        String subject = cboSubjects.getSelectedItem().toString();
        String level = cboDifficultyLevel.getSelectedItem().toString();
        int numberOfQuestions = (Integer)spnNumberOfQuestions.getValue();
        Exam exam = new Exam(subject, level, numberOfQuestions);
        if(exam.list.size()<numberOfQuestions){
            JOptionPane.showMessageDialog(this, "Not Enough Questions in the Database","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int duration = (Integer)spnDuration.getValue();
        ConductExamFrame f = new ConductExamFrame(subject,level,numberOfQuestions,duration);
        f.setLocationRelativeTo(null);
        f.setParentFrame(parent);
        f.setVisible(true);
        this.setVisible(false);
        ((MainFrame)parent).setChild(f);
        dispose();
    }//GEN-LAST:event_StartPanelMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         cboSubjects.setModel(new javax.swing.DefaultComboBoxModel(dbManager.getSubjects()));
        cboDifficultyLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Beginner", "Intermediate", "Expert" }));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
                                              

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StartPanel;
    private javax.swing.JLabel Startlabel;
    private javax.swing.JComboBox cboDifficultyLevel;
    private javax.swing.JComboBox cboSubjects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spnDuration;
    private javax.swing.JSpinner spnNumberOfQuestions;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JFrame parent;
}
